title: Economic Action Plan
email: derek.mackay@gov.scot
description: >- # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://economicactionplan.mygov.scot" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: scotgov
github_username:  scottishgovernment
gtm_code: GTM-52H83Z9
sass:
    sass_dir: assets/_scss
host: 0.0.0.0

# Build settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-redirect-from

collections:
  site-furniture:
    output: true
    permalink: /:name/
    parent: home

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
